### ISSUE TITLE
Update-DatabricksClusterResize cmdlet fails if issued immediately after Start-DatabricksCluster

### ISSUE THREAD

**Issue by parasparekh** [DataThirstLtd/azure.databricks.cicd.tools#102]
I wonder if there is a way to continually check the status of the Databricks cluster, preferably inside a loop, to determine if the cluster is in RUNNING state and only after it is running then issue the command "Update-DatabricksClusterResize".

**Comment by simondmorias** [comment]
You can use use Get-DatabricksCluster in a loop checking the status and using a sleep.
