### ISSUE TITLE
Pulling Secret from Azure keyvault with special characters like : = | ; \ / ?  : error: (400) Bad Request.

### ISSUE THREAD

**Issue by AbhimanyuSharmaMosaic** [DataThirstLtd/azure.databricks.cicd.tools#105]
Hi, In Azure CD pipeline if I am pulling secret from the key vault and if it has special characters like : = | ; \ / ? in the secret value, the "Databricks Secret Deployment task" is failing with error.

System.Net.WebException: The remote server returned an error: (400) Bad Request.
Invoke-RestMethod : {"error_code":"MALFORMED_REQUEST","message":"Invalid JSON given in the body of the request - failed to parse given JSON"}

However, other special charaters like #@!$ are accepted and working fine. If you can please look into it.

**Comment by simondmorias** [comment]
Hi we do url encode the secret before passing. Let me take a play and I'll get back to you. Thanks for reporting it.
