### ISSUE TITLE
Get-DatabricksServicePrincipals returns 404

### ISSUE THREAD

**Issue by DeLeneMirouze** [DataThirstLtd/azure.databricks.cicd.tools#136]
Hello

Not sure I understand how to use **Get-DatabricksServicePrincipals** because I get 404
I run this code:

```
$instanceDb = Get-AzResource `
		-Name $NAME `
		-ExpandProperties
			
$tokenConf = Connect-Databricks ..........
Get-DatabricksServicePrincipals `
		-BearerToken  $tokenConf.token_value `
		-Region $Region `
		-DatabricksId $InstanceDb.properties.workspaceId 
```
	
I checked with only:

`Get-DatabricksServicePrincipals`

Works fine. But this is not what I want to do

What I am missing?

thanks

**Comment by simondmorias** [comment]
If you run Connect-Databricks you do not need to pass the Bearer token, DatabricksId or Region into the Get command (they are only there for backwards compat with the original version.

So you can just run:

```
Get-DatabricksServicePrincipals
```

You will have to filter any results manually if that is the issue?
