### ISSUE TITLE
Enhancement request - Invoke-DatabricksAPIJSON ?

### ISSUE THREAD

**Issue by TakeshiKovacs** [DataThirstLtd/azure.databricks.cicd.tools#141]
Hi Guys

Would it be possible to get support for Invoke-DatabricksAPI to accept a JSON string directly or get a new module that accepts JSON instead of a hash table?
The reasoning behind the request is I would like to store a cluster configuration in its original JSON format in source control.
Currently to deploy it, I would have to convert the original JSON format to a hash table, then pass it to the function, which then converts it back to a JSON.

Cheers
Mat

**Comment by simondmorias** [comment]
Makes sense. I've got some changes to sort this weekend so will take a look. BTW you can pipe JSON to the cluster and job commands if that is what you are trying to do. Though I need to fix another issue where it doesn't match the cluster name if it already exists and create a duplicate (I will deal with that this weekend as well).

**Comment by TakeshiKovacs** [comment]
Thanks Simon!

I will see if the piping will work for us in the mean time.

Cheers
Mat
