### ISSUE TITLE
Issue with running on ADO build agents

### ISSUE THREAD

**Issue by ryanbbrownavanade** [DataThirstLtd/azure.databricks.cicd.tools#149]
Hello, the Get-FolderContents code seems to work locally (Windows 10) but when run on an ADO build agent it gives me the following: 

![image](https://user-images.githubusercontent.com/40359080/96488721-0d76f100-1204-11eb-9417-335d7993afab.png)

Something appears to be going on with the JWTs specifically run on vs2017-win2016 build agents. Super confusing why this is a problem.

**Comment by RichieBzzzt** [comment]
Hello! 403 is forbidden. Are you certain you are authenticating correctly?

**Comment by ryanbbrownavanade** [comment]
@RichieBzzzt  That indeed was the issue with using key vault secrets. I was bungling that. I do however have another issue with 429 problems and I will open another issue for that.
