### ISSUE TITLE
Time sleeping value in Import-DatabricksFolder.ps1 is too low to prevent 429 errors when executing function with -clean flag.

### ISSUE THREAD

**Issue by ryanbbrownavanade** [DataThirstLtd/azure.databricks.cicd.tools#150]
`    if ($Clean) {
        try {
            $ExistingFiles = Get-DatabricksWorkspaceFolder -Path $DatabricksPath
        }
        catch [System.Net.WebException] {
            # A 404 response is expected if the specified workspace does not exist in Databricks
            # In this case, there will be no existing files to clean so the exception can be safely ignored
        }
        foreach ($f in $ExistingFiles) {
            if ($f.object_type -eq "DIRECTORY") {
                Write-Verbose "Removing directory $($f.path)"
                Remove-DatabricksNotebook -Path $f.path -Recursive
            }
            else {
                Write-Verbose "Removing file $($f.path)"
                Remove-DatabricksNotebook -Path $f.path 
            }
            Start-Sleep -Milliseconds 200 # Prevent 429 responses
        }
    }`

This is the execution block of the -clean flag in the Import-DatabricksFolder.ps1 function. The StartSleep  is set to 200 Milliseconds which works fine on my local machine; but I get a 429 error running on a ADO build agent. I'm wondering if the sleep time needs to be upped here, or preferably made into an optional parameter with a default value of 200. 

![image](https://user-images.githubusercontent.com/40359080/96612694-af114780-12c3-11eb-916e-efa864dd2569.png)

**Comment by RichieBzzzt** [comment]
Fixed with #151

**Comment by simondmorias** [comment]
Hopefully this is fixed now - please reopen if you continue to see this.
