### ISSUE TITLE
Option to keep 1st line in notebooks "# Databricks notebook source" intact

### ISSUE THREAD

**Issue by DaveRuijter** [DataThirstLtd/azure.databricks.cicd.tools#164]
I'd love an option to keep the 1st line "# Databricks notebook source" intact.
I prefer to not remove this line from the notebooks because:

1. Tools like [blackbricks](https://pypi.org/project/blackbricks/#usage) depend on this line to be there. They ignore files that don't have this line.
2. Sometimes I manually download notebooks from the Databricks workspace, and then git identifies this line as a change. Not a big deal of course, but I don't want unnecessary 'changed files' in my pull requests :).

A flag that we can set to disable the removal of this header line would be perfect.

**Comment by dsuarez993** [comment]
This is also affecting the new Repos feature, could we get this fix soon?
`https://docs.databricks.com/repos.html#import-sql-and-python-files-as-a-databricks-notebook`

**Comment by simondmorias** [comment]
I need to look into this. There was a reason for it, but I can't remember why now. Leave it with me. Ideally we should leave the file intact in the way Databricks provides it.

**Comment by DaveRuijter** [comment]
I created [this PR](https://github.com/DataThirstLtd/azure.databricks.cicd.tools/pull/167) for it.

**Comment by pmooij** [comment]
excellent improvement @DaveRuijter & @simondmorias, now it's compatible with Databricks Repos as well, as mentioned by @dsuarez993

**Comment by DaveRuijter** [comment]
✔
@simondmorias  you can close this issue
