### ISSUE TITLE
Extend `Add-DatabricksJarJob`: allow setting the maximum concurrent runs

### ISSUE THREAD

**Issue by michael-damatov** [DataThirstLtd/azure.databricks.cicd.tools#173]
Currently, the `Add-DatabricksJarJob` creates only jobs that cannot be started multiple times.

![image](https://user-images.githubusercontent.com/11958365/120177573-dd1b1a80-c208-11eb-8479-59be3a0e3f2f.png)

It would be nice to allow setting the `max_concurrent_runs` parameter defined in the [REST API](https://docs.databricks.com/dev-tools/api/latest/jobs.html).

**Comment by peter11244** [comment]
I would also be interested in the same functionality as part of  `Add-DatabricksNotebookJob`

**Comment by simondmorias** [comment]
Fixed in #182
