### ISSUE TITLE
Add additional plugin to upload Global Init script

### ISSUE THREAD

**Issue by patpicos** [DataThirstLtd/azure.databricks.cicd.tools#2]
Hi

I have developed the following PS script to upload init scripts to databricks. Right now, it only works for global init scripts (no cluster scoped)

I figure it would make sense to increase the value of an existing plugin rather than creating a competing one!

The location variable is the regular verbose "East US 2" rather than the compressed eastus2. It might be good to have that as a drop down list w/ the allowed deployment regions for databricks

```powershell
param
(
    [parameter(Mandatory = $true)] [String] $file,
    [parameter(Mandatory = $true)] [String] $location,
    [parameter(Mandatory = $true)] [String] $databricksAccessToken
)
$location = $location.replace(" ",'').toLower()
# You can write your azure powershell scripts inline here. 
# You can also pass predefined and custom variables to this script using arguments
$path = Split-path $file
$filename = Split-path -leaf $file

$uri ="https://$location.azuredatabricks.net/api/2.0/dbfs/put"
$hdrs = @{}
$hdrs.Add("Authorization","Bearer $databricksAccessToken")
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Write-Host "Replacing CRLF with LF for $file"
$text = [IO.File]::ReadAllText($file) -replace "`r`n", "`n"
[IO.File]::WriteAllText($file, $text)

Write-Host "Encoding $file to BASE64"
$BinaryContents = [System.IO.File]::ReadAllBytes($File)
$EncodedContents = [System.Convert]::ToBase64String($BinaryContents)
$targetPath  = "/databricks/init/$filename"
$Body = @"
{
    "contents": "$EncodedContents",
    "path": "$targetPath",
    "overwrite": "true"
}
"@

Write-Output "Pushing file $File to $TargetPath to REST API: $uri"
Invoke-RestMethod -Uri $uri -Body $Body -Method 'POST' -Headers $hdrs
```

**Comment by simondmorias** [comment]
Thanks Patrick, this looks useful. I'm about to go on leave for two weeks so I won't be able to do anything with this yet. Though if you want to make the change and create a pull request please feel free.

**Comment by simondmorias** [comment]
Added a function called Add-DatabricksFile to support all file types and cover this scenario. If you set thee TargetLocation to /databricks/init then it will be an init script.
Can you test & confirm?
Otherwise I'm going to close this issue shortly.
Thanks
