### ISSUE TITLE
Add-DatabricksLibrary -should use match instead of contains 

### ISSUE THREAD

**Issue by britex** [DataThirstLtd/azure.databricks.cicd.tools#23]
Hello, 
"$LibrarySettings -contains '{' " is always evaluated to false (l.67 & l.73)
I think you should sue a "-match" instead of "-contains", the rest will work like a charm....

best regards, 

Briac

**Comment by simondmorias** [comment]
Thanks. This is fixed in master now and released to PS Gallery in version 1.1.4.
