### ISSUE TITLE
Support Ampersands in Notebook Names for Export-DatabricksFolder

### ISSUE THREAD

**Issue by rtooker** [DataThirstLtd/azure.databricks.cicd.tools#42]
There's an error with Export-DatabricksFolder if the notebook has an ampersand

Errors Set-LocalNotebook : {"error_code":"RESOURCE_DOES_NOT_EXIST","message":"Path 
([the bit before the ampersand] ) doesn't exist."}

Works with CLI.

**Comment by RichieBzzzt** [comment]
Oh wow, I was going to create an issue for this but have just added a PR #70
