### ISSUE TITLE
Files .ipynb are not supported by Import-DatabricksFolder function

### ISSUE THREAD

**Issue by NowinskiK** [DataThirstLtd/azure.databricks.cicd.tools#49]
Currently, those files are being skipped:

> WARNING: File test.ipynb has an unknown extension - skipping file

File with extension .ipynb is just another **Python** files but in form of more complex format (Jupyter).
So, the following line:
`$FileType = @{".py"="PYTHON";".scala"="SCALA";".r"="R";".sql"="SQL" }`
should be extended to:
`$FileType = @{".py"="PYTHON";".scala"="SCALA";".r"="R";".sql"="SQL";".ipynb"="PYTHON" }`
and in that cases in request format should be **JUPYTER**.

**Comment by simondmorias** [comment]
Included in 1.1.13
