### ISSUE TITLE
Add-DatabricksSparkSubmitJob method doesn't provide ClusterId parameter

### ISSUE THREAD

**Issue by NowinskiK** [DataThirstLtd/azure.databricks.cicd.tools#51]
I would like to run a spark code with a job using an existing cluster.
Although I can see the code is ready to pass 'existing_cluster_id' to API, I can't find ClusterId among input params over there.
```
If ($ClusterId){
        $JobBody['existing_cluster_id'] = $ClusterId
```

**Comment by simondmorias** [comment]
SparkSubmit only supports new clusters ( https://docs.databricks.com/api/latest/jobs.html#jobssparksubmittask). Generally you should always create/destroy clusters and control the flow within the execution. Startup time is obviously an issue here, particularly for development work. But that is where I think creating a library or jar is best. Then for Dev execute from a notebook.

**Comment by simondmorias** [comment]
PS. Not closing this right now. Interested in other possible solutions if you have more details on why you need this.

**Comment by NowinskiK** [comment]
Thanks, somehow I missed lead that info.
Only what I need to do is mount BLOB Storage to the cluster in the infrastructure deployment process, so my newly created cluster has just been kicked off, so I don't really want to create a new one.
Probably, I will go with init script.
