### ISSUE TITLE
Method to run existing job

### ISSUE THREAD

**Issue by NowinskiK** [DataThirstLtd/azure.databricks.cicd.tools#52]
I'd like to run a previously created job which doesn't contain any schedule.
I can't find that method.

**Comment by simondmorias** [comment]
Agreed. Also missing the ability to list job history and fetch history. Long weekend coming up I'll see if I can find some time.

**Comment by simondmorias** [comment]
This is proving a problem - I remember now why I omitted these tasks before.
When you execute the run-now API the job doesn't actually start - despite giving you a runid back. If you look at the run id using the runs-get-output command it just comes back null.
I'm going to raise this with Databricks and see what comes back - this may take a while to sort.

**Comment by simondmorias** [comment]
Resolved and released in version [1.1.14](https://www.powershellgallery.com/packages/azure.databricks.cicd.tools/1.1.14)
