### ISSUE TITLE
No option to remove whole folder/workspace

### ISSUE THREAD

**Issue by NowinskiK** [DataThirstLtd/azure.databricks.cicd.tools#55]
API does offer DELETE command for workspaces:
https://docs.databricks.com/api/latest/workspace.html#delete

This cmdlet has been missed in this fantastic module.
Beside simple option of removing the old code from Databricks, I seriously consider to exec that action before IMPORT a folder with notebooks as IMPORT then is trillion times faster than "updating" existing notebooks at the target.
For some reason when you do that - Databricks do remove all steps and deploy it from the source. That delete operation might last dozens of seconds OR raise a timeout giving a misleading message:
> The service at /api/2.0/workspace/import is temporarily unavailable. Please try again later.

This happens when you have ~400 steps in the notebook.

**Comment by simondmorias** [comment]
Added:
```
Remove-DatabricksNotebook -BearerToken $BearerToken -Region $Region -Path $DatabricksPath -Recursive
```

Released to PS Gallery as version 1.1.15
