### ISSUE TITLE
field not found last_activity_time in request get Get-DatabricksCluster 

### ISSUE THREAD

**Issue by Diegoinnova** [DataThirstLtd/azure.databricks.cicd.tools#71]
Hi,

The microsoft assistants have told me that the request service is provided by you and I will report an incident of the lack of the last_activity_time field in the json returned when making the Get-DatabricksCluster request.
SEPTEMBER
This field has disappeared on September 25
![last_activity_time](https://user-images.githubusercontent.com/56677801/67000711-a0082000-f0d8-11e9-8c35-e1cdd6f9bcef.PNG)

**Comment by simondmorias** [comment]
This does not look related to this module - this module does not contain a command called Set-DatabricksEnvironment as shown in your code sample.
