### ISSUE TITLE
Deploy Databricks Job Not found

### ISSUE THREAD

**Issue by mnoncloud** [DataThirstLtd/azure.databricks.cicd.tools#73]
![2019-10-18](https://user-images.githubusercontent.com/16689253/67070425-a44a4100-f19d-11e9-8acc-dbbc49d66a42.png)

I installed the extension in Azure DevOps today, but not able to find the task to deploy jobs. It does have the options for deploying notebooks but not jobs.

**Comment by simondmorias** [comment]
Correct the Azure DevOps tools cannot support all methods because they just have too many options.
Instead add a PowerShell task and run something like:
```
Install-Module azure.databricks.cicd.tools -Scope CurrentUser -Force
Import-Module azure.databricks.cicd.tools
Add-DatabricksPythonJob -BearerToken $BearerToken -Region $Region -JobName "Job1" -SparkVersion "5.3.x-scala2.11" -NodeType "Standard_D3_v2" -MinNumberOfWorkers 2 -MaxNumberOfWorkers 2 -Timeout 100 -MaxRetries 3 -ScheduleCronExpression "0 15 22 ? * *" -Timezone "UTC" -PythonPath "/Shared/TestPython.py" -PythonParameters "val1", "val2" -Libraries '{"pypi":{package:"simplejson"}}', '{"jar": "DBFS:/mylibraries/test.jar"}
```
Full syntax https://github.com/DataThirstLtd/azure.databricks.cicd.tools/wiki
