### ISSUE TITLE
field not found last_activity_time in request get Get-DatabricksClusters

### ISSUE THREAD

**Issue by Diegoinnova** [DataThirstLtd/azure.databricks.cicd.tools#78]
Hi,
I am used  azure.databricks.cicd.tools and I will report an incident of the lack of the last_activity_time field in the json returned when making the Get-DatabricksCluster request. 
This field has disappeared on September 25
![last_activity_time](https://user-images.githubusercontent.com/56677801/67004490-b619de80-f0e0-11e9-8c63-1bcb5dc1cd7a.PNG)

Please i need a answer,thank

**Comment by simondmorias** [comment]
These tools just return what ever the Databricks API sends us. We do not transform the data: https://docs.databricks.com/dev-tools/api/latest/clusters.html#clustergetclusterresponse
Therefore you should take this up with Databricks as the API documentation says it should come back.
