### ISSUE TITLE
Upload a file to Databricks workspace

### ISSUE THREAD

**Issue by matallanas** [DataThirstLtd/azure.databricks.cicd.tools#87]
Hi, I am trying to upload to a databricks with a specific name specified in the target location of command.
However, it creates a folder in which the file is inside.
e.g.
Add-DatabricksDBFSFile -LocalRootFolder "fileToUpload/" -FilePattern "InitScript.sh" -TargetLocation "/databricks/init/init-script.sh"

But in databricks the file is created in --> dbfs:/databricks/init/init-script.sh/InitScript.sh

I can do this with calling the API and making a put.Maybe is interestng to create a Method to uploadfiles directly with the a concrete name.

Thank you very much.

**Comment by simondmorias** [comment]
Your command should be:
```
Add-DatabricksDBFSFile -LocalRootFolder "fileToUpload/" -FilePattern "InitScript.sh" -TargetLocation "/databricks/init/"
```

That will upload the single file.

**Comment by matallanas** [comment]
Yeah I know that I can upload that way, however I want to create it with another name by specifying in the route of the target location. Is it possible?

**Comment by simondmorias** [comment]
Closing as won't fix (sorry). It can be done but not worth the effort. Though would be accepted as PR if you want to do yourself. Thanks for feedback.
