### ISSUE TITLE
Issue with clearing the workspace folder in the "Databricks Deploy Notebooks" release pipeline task

### ISSUE THREAD

**Issue by parasparekh** [DataThirstLtd/azure.databricks.cicd.tools#98]
While trying to clear the target folder in the databricks workspace by checking the property "Clean Workspace Folder" in the notebooks deploy task I see that after copying the notebooks the folder/subfolder/notebook level permissions are lost.
Is this a known issue and if not, how do we prevent the original permissions from being lost ?

**Comment by simondmorias** [comment]
I agree this is an issue. The code deletes the folder and then deploys, so the permissions are dropped. Can be fixed by doing a delete *.* inside the folder instead of deleting the folder. I will aim to fix before end of year.

**Comment by parasparekh** [comment]
Hello Simond, Do you have a definite timeline of when you will be able to fix this ?

**Comment by simondmorias** [comment]
Nope afraid not. For now you could reapply the permissions using a powershell script and the set permission command. https://github.com/DataThirstLtd/azure.databricks.cicd.tools/wiki/Set-DatabricksPermission

**Comment by parasparekh** [comment]
ok, thank you Simond

**Comment by parasparekh** [comment]
Simond, since the Databricks Deploy Notebooks task is first clearing the target folder and then attempting to copy the notebooks, after the task completes you see an empty folder in the target.
Now if I try to use the powershell Set-DatabricksPermission cmdlet to reapply the permissions on the root folder I will once again have to use the Databricks Deploy Notebooks task to copy the notebooks. So the sequence of tasks would be Databricks Deploy Notebooks with clearing the target folder -> Powershell script to reapply permissions on root -> Databricks Deploy Notebooks without clearing the target unless you have a powershell cmdlet to delete the folder.
Let me know your thoughts.

**Comment by parasparekh** [comment]
Moreover "Set-DatabricksPermission" can set permissions only on a cluster, job etc. but not a workspace folder.

**Comment by parasparekh** [comment]
Simond, can you think of any other workaround ?
