### ISSUE TITLE
Always getting 401 Unauthorized -AADSTS7000215: Invalid client secret is provided

### ISSUE THREAD

**Issue by jayendranarumugam** [DataThirstLtd/azure.databricks.cicd.tools#99]
Hi,

I'm always getting 401 while using the SPN Authentication. So I debug it from the Powershell command.

`Connect-Databricks -Region <LOCATION> -ApplicationId <APPLICATION_ID> -Secret <SECRET> -ResourceGroupName <RESOURCE_GROUP_NAME> -SubscriptionId <SUBSCRIPTION_ID> -WorkspaceName <DATABRICKS_NAME> -TenantId <TENANT_ID>`

Using fiddler I get the below 

> {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 34744c89-e0e8-431f-bc20-cbd99292f600\r\nCorrelation ID: c582c863-9180-4ba3-a3f7-aa5826c7f69c\r\nTimestamp: 2019-12-10 10:04:56Z","error_codes":[7000215],"timestamp":"2019-12-10 10:04:56Z","trace_id":"34744c89-e0e8-431f-bc20-cbd99292f600","correlation_id":"c582c863-9180-4ba3-a3f7-aa5826c7f69c","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

I tried with both Standard and Premium Tier but no luck so far.

Also, I tried to encode the client secrets but that also not working.

Using the fiddler I see that there are 2 requests that are going to Microsoft login.

1. grant_type=client_credentials&client_id=xxxx&resource=https://management.core.windows.net/&client_secret=xxxx

2. grant_type=client_credentials&client_id=xxxx&resource=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d&client_secret=xxxx

From the 2 why the resource is hardcoded as **2ff814a6-3304-4ab8-85cb-cd0e6f879c1d** ?

**Comment by simondmorias** [comment]
That guid is a well known guid for the Databricks Enterprise App (https://docs.microsoft.com/en-us/azure/databricks/administration-guide/access-control/conditional-access).

The fact that you see two auth requests shows that your app id and secret are valid - the second request is now requesting a databricks token - which is failing. I suspect the application does not have permission. 

In the azure portal can you go to the Databricks workspace resource. Use the Access Control blade and check the access for your Service Principal? It must have Contributor or Owner access.

**Comment by jayendranarumugam** [comment]
Thanks for the quick response @simondmorias 
I checked the access in the IAM, the SPN has the contributor access. Not sure why the **Invalid client secret is provided** error is coming 

![image](https://user-images.githubusercontent.com/25414541/70534514-40327080-1b81-11ea-8c27-05e7eda2e496.png)

**Comment by simondmorias** [comment]
Odd. Can you go into your Azure AD and look at Enterprise Applications. Then search for that guid you pointed out earlier: 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d

![image](https://user-images.githubusercontent.com/12765000/70536826-5b888600-1b57-11ea-8a42-4acc8841169e.png)

Can you verify the application exists? If not we need to work out why.

**Comment by jayendranarumugam** [comment]
Checked in the AD and it exists as well

![image](https://user-images.githubusercontent.com/25414541/70599807-1d04d100-1c14-11ea-9377-39dcf474ee91.png)

**Comment by jayendranarumugam** [comment]
Hi @simondmorias ,
One update is among the 2 requests, the failing request is 

`grant_type=client_credentials&client_id=xxx&resource=https://management.core.windows.net/&client_secret=xxx`

Giving 

> error_description=AADSTS7000215: Invalid client secret is provided.
> Trace ID: 2e7b3971-14a9-4dfb-8b96-92e65e001a02
> Correlation ID: 90efd3d5-3fff-4927-b0cf-80dedd491ee5
> Timestamp: 2019-12-11 09:52:24Z

The other request below

`grant_type=client_credentials&client_id=xxx&resource=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d&client_secret=xxxx`

is getting success and it returns the access token as well

Do you know what makes the 1st request fails?

**Comment by simondmorias** [comment]
I think this is something to do with url encoding and your secret. I have released a new version 2.0.54 - please can you try 
```powershell
Update-Module azure.databricks.cicd.tools
```
And try again? Thanks

**Comment by jayendranarumugam** [comment]
Thanks @simondmorias  worked like a charm now

**Comment by jayendranarumugam** [comment]
one more thing @simondmorias  where we can able to find the updates of the SPN **Preview to GA** for Azure DataBricks

**Comment by simondmorias** [comment]
You will have to contact your Databricks Account team I'm afraid. I've not been given any information on that I'm afraid.

**Comment by jayendranarumugam** [comment]
For other, I've contacted the databricks team as per them the SPN GA for databricks will be on 2020 Q3
